### ISSUE TITLE
DGIWG WMS suite not listed using REST API

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/ets-dgiwg#10]
Test suites implemented using TestNG can be invoked using the REST API. Available suites are listed when submitting a GET request to the `/teamengine/rest/suites` endpoint,

The ETS for the DGIWG WMS profile does not appear in the list, and selecting the (docs) link on the TEAM Engine home page produces a 404 response.

**Comment by rjmartell** [comment]
Some essential resources are missing:

* src/main/javadoc/{index.html, overview.html}
* src/main/resources/META-INF/services/com.occamlab.te.spi.jaxrs.TestSuiteController

**Comment by rjmartell** [comment]
I added placeholder documentation (from the ETS archetype). The site docs and Javadoc overview should be updated for this test suite.

**Comment by dstenger** [comment]
To be 100% sure.
Following pages are not filled with content, correct?
* http://hostname/teamengine/about/dgiwgwms13/1.3.0/site/index.html
* http://opengeospatial.github.io/ets-dgiwgwms13/apidocs/

**Comment by dstenger** [comment]
Javadoc overview was updated: 29bbeacfff5cfbfa592a6dc1551c3a5cf48fb8da

**Comment by dstenger** [comment]
Site content was updated: 0b7b83d8e6edc98d8ca48f40ae8344cf369f0e5a
