### ISSUE TITLE
DGIWG WFS suite not listed using REST API

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/ets-dgiwg#11]
The ETS for the DGIWG WFS profile does not appear in the list, and selecting the (docs) link on the TEAM Engine home page produces a 404 response.

See #10.

**Comment by rjmartell** [comment]
The default boilerplate text for the Javadoc overview (in src/main/javadoc) should be updated.

**Comment by dstenger** [comment]
Javadoc overview was updated: 29bbeacfff5cfbfa592a6dc1551c3a5cf48fb8da
