### ISSUE TITLE
Find and document services that follow profiles

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-dgiwg#2]
Participants are expected to provide the following services:

1. DGIWG WFS 2.0 Profile (DGIWG-122)
  * LSA-A036 (FCU) with NSG app schema v7.0 (GML, JSON) 
  * FO-A037 (CubeWerx) 

2. NSG WFS 2.0 Profile
  * CMD-A034 (ASU)

3. DGIWG WMS 1.3 (DGIWG-112)
  * CMD-A041 (CubeWerx) 

4. NSG WMS 1.3  Profile (NSG-4036)
   * CMD-A039 (Carbon)

**Note**: The WFS profiles are based on WFS 2.0.2 [OGC 09-025r2](http://docs.opengeospatial.org/is/09-025r2/09-025r2.html).

There is an updated list here: https://portal.opengeospatial.org/wiki/Testbed12/Testbed12Components

**Comment by rjmartell** [comment]
1. DGIWG WFS 2.0 Profile (DGIWG-122)
  * LSA-A036 (FCU) with NSG app schema v7.0 (GML, JSON) 
  * FO-A037 (CubeWerx) 

2. NSG WFS 2.0 Profile
  * CMD-A034 (ASU)

3. DGIWG WMS 1.3 (DGIWG-112)
  * CMD-A041 (CubeWerx) 

4. NSG WMS 1.3  Profile (NSG-4036)
   * CMD-A039 (Carbon)

**Note**: The WFS profiles are based on WFS 2.0.2 [OGC 09-025r2](http://docs.opengeospatial.org/is/09-025r2/09-025r2.html).

**Comment by bermud** [comment]
Thank you. I updated the description of the issue.

**Comment by bermud** [comment]
CubeWerx and FCU have been contacted regarding the WFS - DGIWG 2.0 test.
