### ISSUE TITLE
Update CRS references to be URIs

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/ets-dgiwg#5]
The WFS 2.0.2 specification requires that a conforming implementation recognize a CRS identifier given as a well-known URI. Following [OGC 09-048r3](http://portal.opengeospatial.org/files/?artifact_id=37802) (sec. 4.4), two forms are permitted:

1. 'http' URI (_preferred_), e.g. `http://www.opengis.net/def/crs/EPSG/0/4326`
2. URN (_deprecated_), e.g. `urn:ogc:def:crs:EPSG::4326`

The identifiers appearing in the capabilities document must conform to one of these forms.

**Comment by rjmartell** [comment]
The DGIWG profile requires support for at least the following coordinate reference systems (**Requirement 21**):

* `http://www.opengis.net/def/crs/OGC/1.3/CRS84`
* `http://www.opengis.net/def/crs/EPSG/0/4326`

**Comment by dstenger** [comment]
We are currently fixing this issue.

**Comment by dstenger** [comment]
The missing CRS identifier were added in pull request #6 (more information in the pr).

The pull request has already been merged to the master branch.
