### ISSUE TITLE
Document WFS 2.0 DGIWG test

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-dgiwg#7]
Need to create a src/site folder and document what is the scope of the current tests, links to documents, what it not tested etc.

**Comment by dstenger** [comment]
Richard, is the src/site folder used for profiles? If this is not the case, where should documentation be stored?

**Comment by dstenger** [comment]
Relevant documentation should be written in markdown and stored in src/site.

Documentation can also be done in:
 * readme.txt
 * JavaDoc

**Comment by dstenger** [comment]
Documentation was added by following pull request: https://github.com/opengeospatial/ets-dgiwg/pull/9
